# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/VGA_Dis_Cs.xdc

# IP: ip/vga_pll/vga_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_pll || ORIG_REF_NAME==vga_pll} -quiet] -quiet
