# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.cache/wt [current_project]
set_property parent.project_path D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/rover.jpg.coe
add_files D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/spectrum.png.coe
add_files c:/Users/10943/Desktop/vga_files/rover.jpg.coe
read_verilog -library xil_defaultlib {
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/Command_Parser.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/Mode_Selecter.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/Serial_Interface.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/draw_circle.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/draw_line.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/draw_point.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/draw_rect.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/vga_display_draw.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/vga_driver.v
  D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/new/vga_draw.v
}
read_ip -quiet D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/ip/vga_pll/vga_pll.xci
set_property used_in_implementation false [get_files -all d:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/ip/vga_pll/vga_pll_board.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/ip/vga_pll/vga_pll.xdc]
set_property used_in_implementation false [get_files -all d:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/ip/vga_pll/vga_pll_ooc.xdc]

read_ip -quiet D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/constrs_1/new/VGA_Dis_Cs.xdc
set_property used_in_implementation false [get_files D:/Documents/ILoveStudy/VivadoProjects/VGA3/VGA/VGA_imageDEMO/VGA_imageDEMO.srcs/constrs_1/new/VGA_Dis_Cs.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top vga_draw -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_draw.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_draw_utilization_synth.rpt -pb vga_draw_utilization_synth.pb"
